// <auto-generated />
using System;
using AalstAcademie.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AalstAcademie.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261004160000_UseAccountManagerReferences")]
    partial class UseAccountManagerReferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Category_Name", "typeof(Name) = 'text' AND length(Name) <= 100 AND length(trim(Name)) >= 1 AND instr(Name,char(0)) = 0");

                            t.HasCheckConstraint("CK_Category_NormalizedName", "typeof(NormalizedName) = 'text' AND length(NormalizedName) <= 100 AND length(trim(NormalizedName)) >= 1 AND instr(NormalizedName,char(0)) = 0");

                            t.HasCheckConstraint("CK_Category_Version", "typeof(Version) = 'text' AND length(Version) = 36 AND instr(Version,char(0)) = 0\nAND Version <> '00000000-0000-0000-0000-000000000000'\nAND substr(Version,9,1) = '-' AND substr(Version,14,1) = '-'\nAND substr(Version,19,1) = '-' AND substr(Version,24,1) = '-'\nAND length(replace(Version,'-','')) = 32\nAND replace(Version,'-','') NOT GLOB '*[^0-9A-Fa-f]*'");
                        });
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsibleUserId")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ResponsibleUserId");

                    b.ToTable("Departments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Department_Name", "length(trim(Name)) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.ExternalInstructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("ExternalInstructors", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExternalInstructor_Name", "length(trim(OrganizationName)) BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_ExternalInstructor_Vat", "VatNumber IS NULL OR length(VatNumber) <= 32");
                        });
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.InternalInstructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("InternalInstructors", (string)null);
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Locations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Location_Address", "Address IS NULL OR (typeof(Address) = 'text' AND length(Address) <= 500 AND instr(Address,char(0)) = 0)");

                            t.HasCheckConstraint("CK_Location_Capacity", "typeof(MaximumCapacity) = 'integer' AND MaximumCapacity > 0");

                            t.HasCheckConstraint("CK_Location_Name", "typeof(Name) = 'text' AND length(Name) <= 200 AND length(trim(Name)) >= 1 AND instr(Name,char(0)) = 0");

                            t.HasCheckConstraint("CK_Location_Version", "typeof(Version) = 'text' AND length(Version) = 36 AND instr(Version,char(0)) = 0\nAND Version <> '00000000-0000-0000-0000-000000000000'\nAND substr(Version,9,1) = '-' AND substr(Version,14,1) = '-'\nAND substr(Version,19,1) = '-' AND substr(Version,24,1) = '-'\nAND length(replace(Version,'-','')) = 32\nAND replace(Version,'-','') NOT GLOB '*[^0-9A-Fa-f]*'");
                        });
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivation")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainingMomentId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("TrainingMomentId", "ApplicationUserId")
                        .IsUnique()
                        .HasFilter("Status IN (0,1)");

                    b.HasIndex("TrainingMomentId", "Status");

                    b.ToTable("Registrations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Registration_DecisionReason", "DecisionReason IS NULL OR (typeof(DecisionReason) = 'text' AND length(DecisionReason) <= 1000 AND instr(DecisionReason,char(0)) = 0)");

                            t.HasCheckConstraint("CK_Registration_Motivation", "Motivation IS NULL OR (typeof(Motivation) = 'text' AND length(Motivation) <= 4000 AND instr(Motivation,char(0)) = 0)");

                            t.HasCheckConstraint("CK_Registration_RequestedAtUtc", "typeof(RequestedAtUtc) = 'text' AND length(RequestedAtUtc) = 28 AND instr(RequestedAtUtc,char(0)) = 0 AND RequestedAtUtc GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9][0-9]Z'");

                            t.HasCheckConstraint("CK_Registration_Status", "typeof(Status) = 'integer' AND Status IN (0,1,2,3)");

                            t.HasCheckConstraint("CK_Registration_Version", "typeof(Version) = 'text' AND length(Version) = 36 AND instr(Version,char(0)) = 0\nAND Version <> '00000000-0000-0000-0000-000000000000'\nAND substr(Version,9,1) = '-' AND substr(Version,14,1) = '-'\nAND substr(Version,19,1) = '-' AND substr(Version,24,1) = '-'\nAND length(replace(Version,'-','')) = 32\nAND replace(Version,'-','') NOT GLOB '*[^0-9A-Fa-f]*'");
                        });
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AudienceScope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExternalTotalPriceEuros")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ExternalTotalPriceCents");

                    b.Property<string>("InstructorUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresMotivation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InstructorUserId");

                    b.ToTable("Trainings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Training_Audience", "typeof(AudienceScope) = 'integer' AND AudienceScope IN (0,1,2)");

                            t.HasCheckConstraint("CK_Training_Booleans", "typeof(RequiresMotivation) = 'integer' AND RequiresMotivation IN (0,1)");

                            t.HasCheckConstraint("CK_Training_Description", "Description IS NULL OR (typeof(Description) = 'text' AND length(Description) <= 4000 AND instr(Description,char(0)) = 0)");

                            t.HasCheckConstraint("CK_Training_Instructor", "typeof(InstructorUserId) = 'text' AND length(trim(InstructorUserId)) >= 1 AND instr(InstructorUserId,char(0)) = 0");

                            t.HasCheckConstraint("CK_Training_Price", "ExternalTotalPriceCents IS NULL OR (typeof(ExternalTotalPriceCents) = 'integer' AND ExternalTotalPriceCents >= 0)");

                            t.HasCheckConstraint("CK_Training_Title", "typeof(Title) = 'text' AND length(Title) <= 200 AND length(trim(Title)) >= 1 AND instr(Title,char(0)) = 0");

                            t.HasCheckConstraint("CK_Training_Version", "typeof(Version) = 'text' AND length(Version) = 36 AND instr(Version,char(0)) = 0\nAND Version <> '00000000-0000-0000-0000-000000000000'\nAND substr(Version,9,1) = '-' AND substr(Version,14,1) = '-'\nAND substr(Version,19,1) = '-' AND substr(Version,24,1) = '-'\nAND length(replace(Version,'-','')) = 32\nAND replace(Version,'-','') NOT GLOB '*[^0-9A-Fa-f]*'");
                        });
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.TrainingDepartment", b =>
                {
                    b.Property<int>("TrainingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrainingId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("TrainingDepartments", (string)null);
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.TrainingMoment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("EndTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EndTimeTicks");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StartTimeTicks");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("TrainingId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrainingId");

                    b.HasIndex("LocationId", "Date", "Status", "StartTime");

                    b.ToTable("TrainingMoments", null, t =>
                        {
                            t.HasCheckConstraint("CK_TrainingMoment_Capacity", "typeof(MaximumParticipants) = 'integer' AND MaximumParticipants > 0");

                            t.HasCheckConstraint("CK_TrainingMoment_Date", "typeof(Date) = 'text' AND length(Date) = 10 AND instr(Date,char(0)) = 0 AND Date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'");

                            t.HasCheckConstraint("CK_TrainingMoment_Status", "typeof(Status) = 'integer' AND Status IN (1,2)");

                            t.HasCheckConstraint("CK_TrainingMoment_Time", "typeof(StartTimeTicks) = 'integer' AND typeof(EndTimeTicks) = 'integer' AND StartTimeTicks BETWEEN 0 AND 863999999999 AND EndTimeTicks BETWEEN 0 AND 863999999999 AND EndTimeTicks > StartTimeTicks");

                            t.HasCheckConstraint("CK_TrainingMoment_Version", "typeof(Version) = 'text' AND length(Version) = 36 AND instr(Version,char(0)) = 0\nAND Version <> '00000000-0000-0000-0000-000000000000'\nAND substr(Version,9,1) = '-' AND substr(Version,14,1) = '-'\nAND substr(Version,19,1) = '-' AND substr(Version,24,1) = '-'\nAND length(replace(Version,'-','')) = 32\nAND replace(Version,'-','') NOT GLOB '*[^0-9A-Fa-f]*'");
                        });
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.WaitlistEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JoinedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Motivation")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainingId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("TrainingId", "ApplicationUserId")
                        .IsUnique()
                        .HasFilter("ClosedAtUtc IS NULL");

                    b.HasIndex("TrainingId", "JoinedAtUtc", "Id");

                    b.ToTable("WaitlistEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_WaitlistEntry_ClosedAtUtc", "ClosedAtUtc IS NULL OR (typeof(ClosedAtUtc) = 'text' AND length(ClosedAtUtc) = 28 AND instr(ClosedAtUtc,char(0)) = 0 AND ClosedAtUtc GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9][0-9]Z')");

                            t.HasCheckConstraint("CK_WaitlistEntry_JoinedAtUtc", "typeof(JoinedAtUtc) = 'text' AND length(JoinedAtUtc) = 28 AND instr(JoinedAtUtc,char(0)) = 0 AND JoinedAtUtc GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9][0-9]Z'");

                            t.HasCheckConstraint("CK_WaitlistEntry_Motivation", "Motivation IS NULL OR (typeof(Motivation) = 'text' AND length(Motivation) <= 4000 AND instr(Motivation,char(0)) = 0)");

                            t.HasCheckConstraint("CK_WaitlistEntry_Version", "typeof(Version) = 'text' AND length(Version) = 36 AND instr(Version,char(0)) = 0\nAND Version <> '00000000-0000-0000-0000-000000000000'\nAND substr(Version,9,1) = '-' AND substr(Version,14,1) = '-'\nAND substr(Version,19,1) = '-' AND substr(Version,24,1) = '-'\nAND length(replace(Version,'-','')) = 32\nAND replace(Version,'-','') NOT GLOB '*[^0-9A-Fa-f]*'");
                        });
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountApprovalStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("AccountRequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoSeedKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefusalReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequestedAccountType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DemoSeedKey")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerUserId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("ReviewedById");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Department", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", "ResponsibleUser")
                        .WithMany()
                        .HasForeignKey("ResponsibleUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ResponsibleUser");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.ExternalInstructor", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("AalstAcademie.Web.Models.Domain.ExternalInstructor", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.InternalInstructor", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("AalstAcademie.Web.Models.Domain.InternalInstructor", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Registration", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AalstAcademie.Web.Models.Domain.TrainingMoment", "TrainingMoment")
                        .WithMany("Registrations")
                        .HasForeignKey("TrainingMomentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainingMoment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Training", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Domain.Category", "Category")
                        .WithMany("Trainings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.TrainingDepartment", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Domain.Department", "Department")
                        .WithMany("TrainingDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AalstAcademie.Web.Models.Domain.Training", "Training")
                        .WithMany("TrainingDepartments")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.TrainingMoment", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Domain.Location", "Location")
                        .WithMany("Moments")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AalstAcademie.Web.Models.Domain.Training", "Training")
                        .WithMany("Moments")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.WaitlistEntry", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AalstAcademie.Web.Models.Domain.Training", "Training")
                        .WithMany("WaitlistEntries")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Training");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Identity.ApplicationUser", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Manager");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Category", b =>
                {
                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Department", b =>
                {
                    b.Navigation("TrainingDepartments");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Location", b =>
                {
                    b.Navigation("Moments");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Training", b =>
                {
                    b.Navigation("Moments");

                    b.Navigation("TrainingDepartments");

                    b.Navigation("WaitlistEntries");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.TrainingMoment", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
