// <auto-generated />
using System;
using AalstAcademie.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AalstAcademie.Web.Data.Migrations
{
    // Sprint003: EF-model bij deze migratie, inclusief de ongewijzigde eerdere accountconfiguratie.
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261003125215_AddTrainingManagement")]
    partial class AddTrainingManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .UseCollation("BINARY");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("CK_Category_Name", "typeof(Name) = 'text' AND length(Name) <= 100 AND length(trim(Name)) >= 1 AND instr(Name,char(0)) = 0");

                            t.HasCheckConstraint("CK_Category_NormalizedName", "typeof(NormalizedName) = 'text' AND length(NormalizedName) <= 100 AND length(trim(NormalizedName)) >= 1 AND instr(NormalizedName,char(0)) = 0");

                            t.HasCheckConstraint("CK_Category_Version", "typeof(Version) = 'text' AND length(Version) = 36\nAND Version <> '00000000-0000-0000-0000-000000000000'\nAND substr(Version,9,1) = '-' AND substr(Version,14,1) = '-'\nAND substr(Version,19,1) = '-' AND substr(Version,24,1) = '-'\nAND length(replace(Version,'-','')) = 32\nAND replace(Version,'-','') NOT GLOB '*[^0-9A-Fa-f]*'");
                        });
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Department_Name", "length(trim(Name)) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.ExternalInstructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("ExternalInstructors", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExternalInstructor_Name", "length(trim(OrganizationName)) BETWEEN 1 AND 200");

                            t.HasCheckConstraint("CK_ExternalInstructor_Vat", "VatNumber IS NULL OR length(VatNumber) <= 32");
                        });
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.InternalInstructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("InternalInstructors", (string)null);
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AudienceScope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long>("EndTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EndTimeTicks");

                    b.Property<int?>("ExternalInstructorId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExternalTotalPriceEuros")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ExternalTotalPriceCents");

                    b.Property<int?>("InternalInstructorId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresMotivation")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StartTimeTicks");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExternalInstructorId");

                    b.HasIndex("InternalInstructorId");

                    b.HasIndex("IsArchived", "Date", "StartTime", "Id");

                    b.ToTable("Trainings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Training_Audience", "typeof(AudienceScope) = 'integer' AND AudienceScope IN (0,1,2)");

                            t.HasCheckConstraint("CK_Training_Booleans", "typeof(IsArchived) = 'integer' AND IsArchived IN (0,1) AND typeof(RequiresMotivation) = 'integer' AND RequiresMotivation IN (0,1)");

                            t.HasCheckConstraint("CK_Training_Capacity", "typeof(MaximumParticipants) = 'integer' AND MaximumParticipants > 0");

                            t.HasCheckConstraint("CK_Training_Date", "typeof(Date) = 'text' AND length(Date) = 10 AND Date GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]'");

                            t.HasCheckConstraint("CK_Training_Description", "Description IS NULL OR (typeof(Description) = 'text' AND length(Description) <= 4000)");

                            t.HasCheckConstraint("CK_Training_InstructorXor", "(InternalInstructorId IS NOT NULL AND ExternalInstructorId IS NULL) OR (InternalInstructorId IS NULL AND ExternalInstructorId IS NOT NULL)");

                            t.HasCheckConstraint("CK_Training_Location", "typeof(Location) = 'text' AND length(Location) <= 200 AND length(trim(Location)) >= 1 AND instr(Location,char(0)) = 0");

                            t.HasCheckConstraint("CK_Training_Price", "(InternalInstructorId IS NOT NULL AND ExternalTotalPriceCents IS NULL) OR (ExternalInstructorId IS NOT NULL AND ExternalTotalPriceCents IS NOT NULL AND typeof(ExternalTotalPriceCents) = 'integer' AND ExternalTotalPriceCents >= 0)");

                            t.HasCheckConstraint("CK_Training_Time", "typeof(StartTimeTicks) = 'integer' AND typeof(EndTimeTicks) = 'integer' AND StartTimeTicks BETWEEN 0 AND 863999999999 AND EndTimeTicks BETWEEN 0 AND 863999999999 AND EndTimeTicks > StartTimeTicks");

                            t.HasCheckConstraint("CK_Training_Title", "typeof(Title) = 'text' AND length(Title) <= 200 AND length(trim(Title)) >= 1 AND instr(Title,char(0)) = 0");

                            t.HasCheckConstraint("CK_Training_Version", "typeof(Version) = 'text' AND length(Version) = 36\nAND Version <> '00000000-0000-0000-0000-000000000000'\nAND substr(Version,9,1) = '-' AND substr(Version,14,1) = '-'\nAND substr(Version,19,1) = '-' AND substr(Version,24,1) = '-'\nAND length(replace(Version,'-','')) = 32\nAND replace(Version,'-','') NOT GLOB '*[^0-9A-Fa-f]*'");
                        });
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.TrainingDepartment", b =>
                {
                    b.Property<int>("TrainingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TrainingId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("TrainingDepartments", (string)null);
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountApprovalStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("AccountRequestedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("DemoSeedKey")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefusalReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequestedAccountType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DemoSeedKey")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("ReviewedById");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.ExternalInstructor", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("AalstAcademie.Web.Models.Domain.ExternalInstructor", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.InternalInstructor", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("AalstAcademie.Web.Models.Domain.InternalInstructor", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Training", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Domain.Category", "Category")
                        .WithMany("Trainings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AalstAcademie.Web.Models.Domain.ExternalInstructor", "ExternalInstructor")
                        .WithMany()
                        .HasForeignKey("ExternalInstructorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AalstAcademie.Web.Models.Domain.InternalInstructor", "InternalInstructor")
                        .WithMany()
                        .HasForeignKey("InternalInstructorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("ExternalInstructor");

                    b.Navigation("InternalInstructor");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.TrainingDepartment", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Domain.Department", "Department")
                        .WithMany("TrainingDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AalstAcademie.Web.Models.Domain.Training", "Training")
                        .WithMany("TrainingDepartments")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Identity.ApplicationUser", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Domain.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("ReviewedBy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AalstAcademie.Web.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Category", b =>
                {
                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Department", b =>
                {
                    b.Navigation("TrainingDepartments");
                });

            modelBuilder.Entity("AalstAcademie.Web.Models.Domain.Training", b =>
                {
                    b.Navigation("TrainingDepartments");
                });
#pragma warning restore 612, 618
        }
    }
}
